# Generated by Django 5.2.4 on 2025-07-30 15:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del equipo médico', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Nombre del Equipo Médico')),
                ('brand', models.CharField(help_text='Marca del equipo médico', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Marca')),
                ('series', models.CharField(help_text='Número de serie del equipo', max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='Serie')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del equipo médico', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del equipo médico', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo Médico',
                'verbose_name_plural': 'Equipos Médicos',
                'ordering': ['name', 'brand'],
                'indexes': [models.Index(fields=['name'], name='cotizacion__name_91c17a_idx'), models.Index(fields=['brand'], name='cotizacion__brand_c834ce_idx'), models.Index(fields=['series'], name='cotizacion__series_c24bb9_idx')],
            },
        ),
    ]
